// SIC to Sector/Industry Mapping
// Static, deterministic mapping based on SIC code ranges
// No external dependencies - all mapping logic is local

/**
 * Maps SIC code to sector and industry
 * Based on SEC SIC classification structure
 */
export interface SICMapping {
  sector: string;
  industry: string;
}

/**
 * SIC code ranges and their corresponding sectors/industries
 * Organized by major division
 */
const SIC_MAP: Record<string, { sector: string; industry: string }> = {
  // Agriculture, Forestry, Fishing (01-09)
  '0100': { sector: 'Basic Materials', industry: 'Agriculture' },
  '0200': { sector: 'Basic Materials', industry: 'Agriculture' },
  
  // Mining and Construction (10-17)
  '1000': { sector: 'Basic Materials', industry: 'Metals & Mining' },
  '1300': { sector: 'Energy', industry: 'Oil & Gas' },
  '1380': { sector: 'Energy', industry: 'Oil & Gas Services' },
  '1400': { sector: 'Basic Materials', industry: 'Construction Materials' },
  
  // Manufacturing (20-39)
  '2000': { sector: 'Consumer Cyclical', industry: 'Packaging & Containers' },
  '2100': { sector: 'Consumer Cyclical', industry: 'Tobacco' },
  '2200': { sector: 'Consumer Cyclical', industry: 'Textiles' },
  '2300': { sector: 'Consumer Cyclical', industry: 'Apparel' },
  '2400': { sector: 'Basic Materials', industry: 'Forest Products' },
  '2500': { sector: 'Consumer Cyclical', industry: 'Furnishings' },
  '2600': { sector: 'Basic Materials', industry: 'Paper Products' },
  '2700': { sector: 'Communication Services', industry: 'Publishing' },
  '2800': { sector: 'Healthcare', industry: 'Pharmaceuticals' },
  '2830': { sector: 'Healthcare', industry: 'Biotechnology' },
  '2840': { sector: 'Consumer Defensive', industry: 'Household Products' },
  '2850': { sector: 'Consumer Defensive', industry: 'Household Products' },
  '2860': { sector: 'Basic Materials', industry: 'Chemicals' },
  '2870': { sector: 'Basic Materials', industry: 'Fertilizers & Agricultural Chemicals' },
  '2890': { sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  '2900': { sector: 'Energy', industry: 'Oil & Gas Refining' },
  '2910': { sector: 'Energy', industry: 'Oil & Gas Refining' },
  '2950': { sector: 'Basic Materials', industry: 'Asphalt & Road Oiling' },
  '2990': { sector: 'Energy', industry: 'Oil & Gas Refining' },
  '3010': { sector: 'Consumer Cyclical', industry: 'Tires & Rubber' },
  '3020': { sector: 'Consumer Cyclical', industry: 'Tires & Rubber' },
  '3080': { sector: 'Consumer Cyclical', industry: 'Plastics' },
  '3100': { sector: 'Consumer Cyclical', industry: 'Footwear' },
  '3140': { sector: 'Consumer Cyclical', industry: 'Footwear' },
  '3200': { sector: 'Basic Materials', industry: 'Glass & Glass Products' },
  '3210': { sector: 'Basic Materials', industry: 'Building Materials' },
  '3240': { sector: 'Basic Materials', industry: 'Cement' },
  '3250': { sector: 'Basic Materials', industry: 'Clay & Concrete Products' },
  '3260': { sector: 'Consumer Cyclical', industry: 'Pottery & Related Products' },
  '3270': { sector: 'Basic Materials', industry: 'Concrete, Gypsum & Plaster' },
  '3280': { sector: 'Basic Materials', industry: 'Cut Stone & Stone Products' },
  '3290': { sector: 'Basic Materials', industry: 'Abrasive & Nonmetallic Minerals' },
  '3310': { sector: 'Basic Materials', industry: 'Steel' },
  '3320': { sector: 'Basic Materials', industry: 'Iron & Steel' },
  '3330': { sector: 'Basic Materials', industry: 'Primary Metals' },
  '3340': { sector: 'Technology', industry: 'Computer Hardware' },
  '3350': { sector: 'Basic Materials', industry: 'Nonferrous Metals' },
  '3360': { sector: 'Consumer Cyclical', industry: 'Automotive' },
  '3400': { sector: 'Industrial', industry: 'Industrial Machinery' },
  '3420': { sector: 'Industrial', industry: 'Cutlery & Hand Tools' },
  '3440': { sector: 'Industrial', industry: 'Fabricated Metal Products' },
  '3450': { sector: 'Industrial', industry: 'Screw Machine Products' },
  '3460': { sector: 'Industrial', industry: 'Metal Forgings & Stampings' },
  '3470': { sector: 'Consumer Cyclical', industry: 'Coating & Engraving' },
  '3480': { sector: 'Industrial', industry: 'Ordnance & Accessories' },
  '3490': { sector: 'Industrial', industry: 'Miscellaneous Fabricated Metal' },
  '3510': { sector: 'Industrial', industry: 'Engines & Turbines' },
  '3520': { sector: 'Consumer Cyclical', industry: 'Farm & Construction Machinery' },
  '3530': { sector: 'Consumer Cyclical', industry: 'Construction & Agriculture Machinery' },
  '3540': { sector: 'Industrial', industry: 'Metalworking Machinery' },
  '3550': { sector: 'Consumer Cyclical', industry: 'Special Industry Machinery' },
  '3560': { sector: 'Industrial', industry: 'General Industrial Machinery' },
  '3570': { sector: 'Technology', industry: 'Computer Hardware' },
  '3580': { sector: 'Consumer Cyclical', industry: 'Refrigeration & Service Machinery' },
  '3590': { sector: 'Industrial', industry: 'Industrial Machinery' },
  '3600': { sector: 'Technology', industry: 'Electronic Components' },
  '3610': { sector: 'Technology', industry: 'Electronic Components' },
  '3620': { sector: 'Technology', industry: 'Electronic Components' },
  '3630': { sector: 'Consumer Cyclical', industry: 'Household Appliances' },
  '3640': { sector: 'Technology', industry: 'Electronic Components' },
  '3650': { sector: 'Consumer Cyclical', industry: 'Household Appliances' },
  '3660': { sector: 'Technology', industry: 'Telecommunications Equipment' },
  '3670': { sector: 'Technology', industry: 'Electronic Components' },
  '3680': { sector: 'Technology', industry: 'Electronic Components' },
  '3690': { sector: 'Technology', industry: 'Electronic Components' },
  '3710': { sector: 'Consumer Cyclical', industry: 'Automotive' },
  '3720': { sector: 'Industrial', industry: 'Aerospace & Defense' },
  '3730': { sector: 'Consumer Cyclical', industry: 'Recreational Vehicles' },
  '3740': { sector: 'Consumer Cyclical', industry: 'Railroad Equipment' },
  '3750': { sector: 'Consumer Cyclical', industry: 'Motorcycles & Bicycles' },
  '3760': { sector: 'Industrial', industry: 'Guided Missiles & Space Vehicles' },
  '3790': { sector: 'Industrial', industry: 'Transportation Equipment' },
  '3810': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  '3820': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  '3830': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  '3840': { sector: 'Healthcare', industry: 'Medical Devices' },
  '3850': { sector: 'Healthcare', industry: 'Medical Devices' },
  '3860': { sector: 'Technology', industry: 'Photographic Equipment' },
  '3870': { sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  '3910': { sector: 'Consumer Cyclical', industry: 'Jewelry & Silverware' },
  '3930': { sector: 'Consumer Cyclical', industry: 'Musical Instruments' },
  '3940': { sector: 'Consumer Cyclical', industry: 'Toys & Games' },
  '3950': { sector: 'Consumer Cyclical', industry: 'Pens, Pencils & Office Supplies' },
  '3960': { sector: 'Consumer Cyclical', industry: 'Costume Jewelry' },
  '3990': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Manufacturing' },
  
  // Transportation and Utilities (40-49)
  '4010': { sector: 'Industrial', industry: 'Railroads' },
  '4110': { sector: 'Industrial', industry: 'Trucking' },
  '4120': { sector: 'Industrial', industry: 'Trucking' },
  '4130': { sector: 'Consumer Cyclical', industry: 'Passenger Transportation' },
  '4140': { sector: 'Industrial', industry: 'Freight Transportation' },
  '4150': { sector: 'Consumer Cyclical', industry: 'School Buses' },
  '4170': { sector: 'Industrial', industry: 'Transportation Services' },
  '4190': { sector: 'Industrial', industry: 'Transportation Services' },
  '4200': { sector: 'Industrial', industry: 'Trucking & Warehousing' },
  '4210': { sector: 'Industrial', industry: 'Trucking' },
  '4220': { sector: 'Industrial', industry: 'Public Warehousing' },
  '4230': { sector: 'Industrial', industry: 'Trucking' },
  '4240': { sector: 'Industrial', industry: 'Trucking' },
  '4290': { sector: 'Industrial', industry: 'Freight Transportation' },
  '4310': { sector: 'Communication Services', industry: 'Postal Services' },
  '4400': { sector: 'Industrial', industry: 'Marine Transportation' },
  '4420': { sector: 'Industrial', industry: 'Marine Transportation' },
  '4430': { sector: 'Industrial', industry: 'Marine Transportation' },
  '4440': { sector: 'Industrial', industry: 'Marine Transportation' },
  '4480': { sector: 'Consumer Cyclical', industry: 'Water Transportation' },
  '4490': { sector: 'Industrial', industry: 'Marine Transportation' },
  '4510': { sector: 'Industrial', industry: 'Air Freight & Logistics' },
  '4520': { sector: 'Consumer Cyclical', industry: 'Airlines' },
  '4530': { sector: 'Consumer Cyclical', industry: 'Air Freight & Logistics' },
  '4580': { sector: 'Industrial', industry: 'Air Services' },
  '4600': { sector: 'Industrial', industry: 'Railroads' },
  '4610': { sector: 'Energy', industry: 'Pipeline Transportation' },
  '4620': { sector: 'Energy', industry: 'Pipeline Transportation' },
  '4630': { sector: 'Energy', industry: 'Pipeline Transportation' },
  '4640': { sector: 'Energy', industry: 'Pipeline Transportation' },
  '4690': { sector: 'Industrial', industry: 'Transportation Services' },
  '4700': { sector: 'Industrial', industry: 'Transportation Services' },
  '4710': { sector: 'Consumer Cyclical', industry: 'Freight Transportation' },
  '4720': { sector: 'Consumer Cyclical', industry: 'Passenger Transportation' },
  '4730': { sector: 'Industrial', industry: 'Transportation Services' },
  '4740': { sector: 'Industrial', industry: 'Railroads' },
  '4780': { sector: 'Industrial', industry: 'Transportation Services' },
  '4810': { sector: 'Communication Services', industry: 'Telecommunications' },
  '4820': { sector: 'Communication Services', industry: 'Telecommunications' },
  '4830': { sector: 'Communication Services', industry: 'Broadcasting' },
  '4840': { sector: 'Communication Services', industry: 'Cable & Satellite' },
  '4890': { sector: 'Communication Services', industry: 'Telecommunications' },
  '4900': { sector: 'Utilities', industry: 'Electric Utilities' },
  '4910': { sector: 'Utilities', industry: 'Electric Utilities' },
  '4920': { sector: 'Utilities', industry: 'Gas Utilities' },
  '4930': { sector: 'Utilities', industry: 'Electric Utilities' },
  '4940': { sector: 'Utilities', industry: 'Water Utilities' },
  '4950': { sector: 'Utilities', industry: 'Sanitary Services' },
  '4960': { sector: 'Utilities', industry: 'Steam & Air Conditioning' },
  '4970': { sector: 'Energy', industry: 'Pipeline Transportation' },
  '4990': { sector: 'Utilities', industry: 'Utilities' },
  
  // Wholesale Trade (50-51)
  '5010': { sector: 'Consumer Cyclical', industry: 'Motor Vehicles & Parts' },
  '5020': { sector: 'Consumer Cyclical', industry: 'Furniture & Home Furnishings' },
  '5030': { sector: 'Consumer Cyclical', industry: 'Lumber & Construction Materials' },
  '5040': { sector: 'Consumer Cyclical', industry: 'Professional Equipment' },
  '5050': { sector: 'Industrial', industry: 'Metals & Minerals' },
  '5060': { sector: 'Consumer Cyclical', industry: 'Electronics & Appliances' },
  '5070': { sector: 'Consumer Cyclical', industry: 'Hardware' },
  '5080': { sector: 'Industrial', industry: 'Machinery & Equipment' },
  '5090': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Durable Goods' },
  '5110': { sector: 'Consumer Cyclical', industry: 'Paper & Paper Products' },
  '5120': { sector: 'Consumer Defensive', industry: 'Drugs & Pharmaceuticals' },
  '5130': { sector: 'Consumer Defensive', industry: 'Apparel & Accessories' },
  '5140': { sector: 'Consumer Defensive', industry: 'Groceries' },
  '5150': { sector: 'Consumer Defensive', industry: 'Farm Products' },
  '5160': { sector: 'Consumer Defensive', industry: 'Chemicals & Allied Products' },
  '5170': { sector: 'Consumer Defensive', industry: 'Petroleum Products' },
  '5180': { sector: 'Consumer Defensive', industry: 'Beer & Wine' },
  '5190': { sector: 'Consumer Defensive', industry: 'Miscellaneous Nondurable Goods' },
  
  // Retail Trade (52-59)
  '5210': { sector: 'Consumer Cyclical', industry: 'Lumber & Building Materials' },
  '5230': { sector: 'Consumer Cyclical', industry: 'Paint & Wallpaper' },
  '5260': { sector: 'Consumer Cyclical', industry: 'Retail - Misc' },
  '5270': { sector: 'Consumer Cyclical', industry: 'Mobile Home Dealers' },
  '5300': { sector: 'Consumer Defensive', industry: 'Department Stores' },
  '5310': { sector: 'Consumer Defensive', industry: 'Department Stores' },
  '5330': { sector: 'Consumer Defensive', industry: 'Variety Stores' },
  '5390': { sector: 'Consumer Defensive', industry: 'Miscellaneous General Merchandise' },
  '5400': { sector: 'Consumer Defensive', industry: 'Grocery Stores' },
  '5410': { sector: 'Consumer Defensive', industry: 'Grocery Stores' },
  '5420': { sector: 'Consumer Defensive', industry: 'Meat & Fish Markets' },
  '5430': { sector: 'Consumer Defensive', industry: 'Fruit & Vegetable Markets' },
  '5440': { sector: 'Consumer Defensive', industry: 'Candy & Nut Stores' },
  '5450': { sector: 'Consumer Defensive', industry: 'Dairy Products Stores' },
  '5460': { sector: 'Consumer Defensive', industry: 'Retail Bakeries' },
  '5490': { sector: 'Consumer Defensive', industry: 'Miscellaneous Food Stores' },
  '5510': { sector: 'Consumer Cyclical', industry: 'Auto Dealers' },
  '5520': { sector: 'Consumer Cyclical', industry: 'Auto Dealers' },
  '5530': { sector: 'Consumer Cyclical', industry: 'Auto & Home Supply Stores' },
  '5540': { sector: 'Consumer Cyclical', industry: 'Gasoline Service Stations' },
  '5550': { sector: 'Consumer Cyclical', industry: 'Boat Dealers' },
  '5560': { sector: 'Consumer Cyclical', industry: 'Recreational Vehicle Dealers' },
  '5570': { sector: 'Consumer Cyclical', industry: 'Motorcycle Dealers' },
  '5590': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Vehicle Dealers' },
  '5610': { sector: 'Consumer Cyclical', industry: 'Furniture Stores' },
  '5620': { sector: 'Consumer Cyclical', industry: 'Floor Covering Stores' },
  '5630': { sector: 'Consumer Cyclical', industry: 'Curtain & Drapery Stores' },
  '5640': { sector: 'Consumer Cyclical', industry: 'Luggage & Leather Goods Stores' },
  '5650': { sector: 'Consumer Cyclical', industry: 'Clothing Stores' },
  '5660': { sector: 'Consumer Cyclical', industry: 'Shoe Stores' },
  '5690': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Apparel & Accessories' },
  '5710': { sector: 'Consumer Cyclical', industry: 'Furniture & Home Furnishings' },
  '5720': { sector: 'Consumer Cyclical', industry: 'Household Appliance Stores' },
  '5730': { sector: 'Consumer Cyclical', industry: 'Radio, TV & Electronics Stores' },
  '5731': { sector: 'Consumer Cyclical', industry: 'Radio, TV & Electronics Stores' },
  '5734': { sector: 'Consumer Cyclical', industry: 'Computer & Software Stores' },
  '5735': { sector: 'Consumer Cyclical', industry: 'Record & Prerecorded Tape Stores' },
  '5736': { sector: 'Consumer Cyclical', industry: 'Musical Instrument Stores' },
  '5750': { sector: 'Consumer Cyclical', industry: 'Auto & Home Supply Stores' },
  '5810': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  '5812': { sector: 'Consumer Cyclical', industry: 'Restaurants' },
  '5813': { sector: 'Consumer Cyclical', industry: 'Drinking Places' },
  '5910': { sector: 'Consumer Defensive', industry: 'Drug Stores' },
  '5920': { sector: 'Consumer Defensive', industry: 'Liquor Stores' },
  '5930': { sector: 'Consumer Cyclical', industry: 'Used Merchandise Stores' },
  '5940': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Shopping Goods' },
  '5941': { sector: 'Consumer Cyclical', industry: 'Sporting Goods Stores' },
  '5942': { sector: 'Consumer Cyclical', industry: 'Book Stores' },
  '5943': { sector: 'Consumer Cyclical', industry: 'Stationery Stores' },
  '5944': { sector: 'Consumer Cyclical', industry: 'Jewelry Stores' },
  '5945': { sector: 'Consumer Cyclical', industry: 'Hobby, Toy & Game Stores' },
  '5946': { sector: 'Consumer Cyclical', industry: 'Camera & Photo Supply Stores' },
  '5947': { sector: 'Consumer Cyclical', industry: 'Gift Stores' },
  '5948': { sector: 'Consumer Cyclical', industry: 'Luggage & Leather Goods Stores' },
  '5949': { sector: 'Consumer Cyclical', industry: 'Sewing & Needlework Stores' },
  '5960': { sector: 'Consumer Cyclical', industry: 'Mail Order Houses' },
  '5980': { sector: 'Energy', industry: 'Fuel Dealers' },
  '5990': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Retail' },
  '5992': { sector: 'Consumer Cyclical', industry: 'Florists' },
  '5993': { sector: 'Consumer Cyclical', industry: 'Tobacco Stores' },
  '5994': { sector: 'Consumer Cyclical', industry: 'News Dealers' },
  '5995': { sector: 'Consumer Cyclical', industry: 'Optical Goods Stores' },
  '5999': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Retail' },
  
  // Finance, Insurance, Real Estate (60-67)
  '6010': { sector: 'Financial Services', industry: 'Commercial Banks' },
  '6020': { sector: 'Financial Services', industry: 'Commercial Banks' },
  '6030': { sector: 'Financial Services', industry: 'Savings Institutions' },
  '6035': { sector: 'Financial Services', industry: 'Savings Institutions' },
  '6036': { sector: 'Financial Services', industry: 'Savings Institutions' },
  '6040': { sector: 'Financial Services', industry: 'Credit Unions' },
  '6060': { sector: 'Financial Services', industry: 'Commercial Banks' },
  '6080': { sector: 'Financial Services', industry: 'Foreign Banks' },
  '6090': { sector: 'Financial Services', industry: 'Functions Related to Depository Banking' },
  '6110': { sector: 'Financial Services', industry: 'Federal & Federally-Sponsored Credit' },
  '6140': { sector: 'Financial Services', industry: 'Personal Credit Institutions' },
  '6150': { sector: 'Financial Services', industry: 'Short-Term Business Credit' },
  '6160': { sector: 'Financial Services', industry: 'Business Credit' },
  '6170': { sector: 'Financial Services', industry: 'Finance Companies' },
  '6190': { sector: 'Financial Services', industry: 'Functions Related to Depository Banking' },
  '6200': { sector: 'Financial Services', industry: 'Security Brokers & Dealers' },
  '6210': { sector: 'Financial Services', industry: 'Security Brokers & Dealers' },
  '6220': { sector: 'Financial Services', industry: 'Commodity Brokers' },
  '6230': { sector: 'Financial Services', industry: 'Security & Commodity Exchanges' },
  '6240': { sector: 'Financial Services', industry: 'Investment Advice' },
  '6280': { sector: 'Financial Services', industry: 'Services Allied With Exchange of Securities' },
  '6290': { sector: 'Financial Services', industry: 'Miscellaneous Investing' },
  '6310': { sector: 'Financial Services', industry: 'Life Insurance' },
  '6320': { sector: 'Financial Services', industry: 'Accident & Health Insurance' },
  '6330': { sector: 'Financial Services', industry: 'Fire, Marine & Casualty Insurance' },
  '6350': { sector: 'Financial Services', industry: 'Surety Insurance' },
  '6360': { sector: 'Financial Services', industry: 'Title Insurance' },
  '6370': { sector: 'Financial Services', industry: 'Pension, Health & Welfare Funds' },
  '6390': { sector: 'Financial Services', industry: 'Insurance' },
  '6410': { sector: 'Financial Services', industry: 'Insurance Agents, Brokers & Service' },
  '6500': { sector: 'Real Estate', industry: 'Real Estate' },
  '6510': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6512': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6513': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6514': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6515': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6517': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6519': { sector: 'Real Estate', industry: 'Real Estate Operators' },
  '6530': { sector: 'Real Estate', industry: 'Real Estate Agents & Managers' },
  '6540': { sector: 'Real Estate', industry: 'Title Abstract Offices' },
  '6550': { sector: 'Real Estate', industry: 'Land Subdividers & Developers' },
  '6560': { sector: 'Real Estate', industry: 'Real Estate Investment Trusts' },
  '6590': { sector: 'Real Estate', industry: 'Real Estate' },
  '6610': { sector: 'Financial Services', industry: 'Combined Real Estate, Insurance, etc.' },
  '6620': { sector: 'Financial Services', industry: 'Real Estate Investment Trusts' },
  '6700': { sector: 'Financial Services', industry: 'Holding & Other Investment Offices' },
  '6710': { sector: 'Financial Services', industry: 'Holding & Other Investment Offices' },
  '6712': { sector: 'Financial Services', industry: 'Office of Bank Holding Companies' },
  '6719': { sector: 'Financial Services', industry: 'Holding Companies' },
  '6720': { sector: 'Financial Services', industry: 'Management Investment Offices' },
  '6722': { sector: 'Financial Services', industry: 'Management Investment Offices, Open-End' },
  '6726': { sector: 'Financial Services', industry: 'Management Investment Offices, Closed-End' },
  '6730': { sector: 'Financial Services', industry: 'Trusts' },
  '6732': { sector: 'Financial Services', industry: 'Educational, Religious & Charitable Trusts' },
  '6733': { sector: 'Financial Services', industry: 'Trusts, Except Educational, Religious & Charitable' },
  '6740': { sector: 'Financial Services', industry: 'Miscellaneous Investing' },
  '6790': { sector: 'Financial Services', industry: 'Miscellaneous Investing' },
  '6792': { sector: 'Financial Services', industry: 'Oil Royalty Traders' },
  '6794': { sector: 'Financial Services', industry: 'Patent Owners & Lessors' },
  '6795': { sector: 'Financial Services', industry: 'Mineral Royalty Traders' },
  '6798': { sector: 'Financial Services', industry: 'Real Estate Investment Trusts' },
  '6799': { sector: 'Financial Services', industry: 'Miscellaneous Investing' },
  
  // Services (70-89)
  '7000': { sector: 'Consumer Cyclical', industry: 'Hotels & Motels' },
  '7010': { sector: 'Consumer Cyclical', industry: 'Hotels & Motels' },
  '7020': { sector: 'Consumer Cyclical', industry: 'Rooming & Boarding Houses' },
  '7030': { sector: 'Consumer Cyclical', industry: 'Camps & Recreational Vehicle Parks' },
  '7040': { sector: 'Consumer Cyclical', industry: 'Organization Hotels & Membership Lodging' },
  '7210': { sector: 'Consumer Cyclical', industry: 'Laundry Services' },
  '7220': { sector: 'Consumer Cyclical', industry: 'Photographic Studios' },
  '7230': { sector: 'Consumer Cyclical', industry: 'Beauty Shops' },
  '7240': { sector: 'Consumer Cyclical', industry: 'Barber Shops' },
  '7250': { sector: 'Consumer Cyclical', industry: 'Shoe Repair & Shine Parlors' },
  '7260': { sector: 'Consumer Cyclical', industry: 'Funeral Service & Crematories' },
  '7290': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Personal Services' },
  '7310': { sector: 'Communication Services', industry: 'Advertising' },
  '7320': { sector: 'Communication Services', industry: 'Consumer Credit Reporting Agencies' },
  '7330': { sector: 'Communication Services', industry: 'Mailing, Reproduction & Stenographic' },
  '7340': { sector: 'Consumer Cyclical', industry: 'Services to Dwellings & Other Buildings' },
  '7350': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Equipment Rental & Leasing' },
  '7360': { sector: 'Technology', industry: 'Employment Agencies' },
  '7370': { sector: 'Technology', industry: 'Software' },
  '7371': { sector: 'Technology', industry: 'Software' },
  '7372': { sector: 'Technology', industry: 'Software' },
  '7373': { sector: 'Technology', industry: 'Software' },
  '7374': { sector: 'Technology', industry: 'Computer Programming' },
  '7375': { sector: 'Technology', industry: 'Information Retrieval Services' },
  '7376': { sector: 'Technology', industry: 'Computer Facilities Management' },
  '7377': { sector: 'Technology', industry: 'Computer Rental & Leasing' },
  '7378': { sector: 'Technology', industry: 'Computer Maintenance & Repair' },
  '7379': { sector: 'Technology', industry: 'Computer Related Services' },
  '7380': { sector: 'Technology', industry: 'Miscellaneous Business Services' },
  '7381': { sector: 'Technology', industry: 'Detective & Armored Car Services' },
  '7382': { sector: 'Technology', industry: 'Security Systems Services' },
  '7383': { sector: 'Technology', industry: 'News Syndicates' },
  '7384': { sector: 'Technology', industry: 'Photofinishing Laboratories' },
  '7385': { sector: 'Technology', industry: 'Telephone Interconnect Systems' },
  '7389': { sector: 'Technology', industry: 'Business Services' },
  '7500': { sector: 'Consumer Cyclical', industry: 'Automotive Repair Services' },
  '7510': { sector: 'Consumer Cyclical', industry: 'Auto Rental & Leasing' },
  '7513': { sector: 'Consumer Cyclical', industry: 'Truck Rental & Leasing' },
  '7514': { sector: 'Consumer Cyclical', industry: 'Passenger Car Rental' },
  '7515': { sector: 'Consumer Cyclical', industry: 'Passenger Car Leasing' },
  '7519': { sector: 'Consumer Cyclical', industry: 'Utility Trailer & Recreational Vehicle Rental' },
  '7520': { sector: 'Consumer Cyclical', industry: 'Automotive Parking' },
  '7530': { sector: 'Consumer Cyclical', industry: 'Automotive Repair Shops' },
  '7532': { sector: 'Consumer Cyclical', industry: 'Top & Body Repair & Paint Shops' },
  '7533': { sector: 'Consumer Cyclical', industry: 'Automotive Exhaust System Repair' },
  '7534': { sector: 'Consumer Cyclical', industry: 'Tire Retreading & Repair Shops' },
  '7536': { sector: 'Consumer Cyclical', industry: 'Automotive Glass Replacement Shops' },
  '7537': { sector: 'Consumer Cyclical', industry: 'Automotive Transmission Repair' },
  '7538': { sector: 'Consumer Cyclical', industry: 'General Automotive Repair' },
  '7539': { sector: 'Consumer Cyclical', industry: 'Automotive Repair Shops' },
  '7540': { sector: 'Consumer Cyclical', industry: 'Automotive Services' },
  '7542': { sector: 'Consumer Cyclical', industry: 'Car Washes' },
  '7549': { sector: 'Consumer Cyclical', industry: 'Automotive Services' },
  '7600': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Repair Services' },
  '7620': { sector: 'Consumer Cyclical', industry: 'Radio & Television Repair' },
  '7622': { sector: 'Consumer Cyclical', industry: 'Radio & Television Repair' },
  '7623': { sector: 'Consumer Cyclical', industry: 'Refrigeration & Air Conditioning Service' },
  '7629': { sector: 'Consumer Cyclical', industry: 'Electrical & Electronic Repair Shops' },
  '7630': { sector: 'Consumer Cyclical', industry: 'Watch, Clock & Jewelry Repair' },
  '7640': { sector: 'Consumer Cyclical', industry: 'Reupholstery & Furniture Repair' },
  '7690': { sector: 'Consumer Cyclical', industry: 'Miscellaneous Repair Shops' },
  '7800': { sector: 'Communication Services', industry: 'Services' },
  '7810': { sector: 'Communication Services', industry: 'Motion Picture Production' },
  '7820': { sector: 'Communication Services', industry: 'Motion Picture Distribution' },
  '7830': { sector: 'Communication Services', industry: 'Motion Picture Theaters' },
  '7840': { sector: 'Communication Services', industry: 'Video Tape Rental' },
  '7900': { sector: 'Communication Services', industry: 'Services' },
  '7910': { sector: 'Communication Services', industry: 'Dance Studios, Schools & Halls' },
  '7920': { sector: 'Communication Services', industry: 'Producers, Orchestras & Entertainers' },
  '7922': { sector: 'Communication Services', industry: 'Theatrical Producers & Ticket Agencies' },
  '7929': { sector: 'Communication Services', industry: 'Bands, Orchestras, Actors & Other Entertainers' },
  '7930': { sector: 'Communication Services', industry: 'Bowling Centers' },
  '7940': { sector: 'Communication Services', industry: 'Commercial Sports' },
  '7948': { sector: 'Communication Services', industry: 'Racing, Including Track Operation' },
  '7990': { sector: 'Communication Services', industry: 'Miscellaneous Amusement & Recreation' },
  '7991': { sector: 'Communication Services', industry: 'Physical Fitness Facilities' },
  '7992': { sector: 'Communication Services', industry: 'Public Golf Courses' },
  '7993': { sector: 'Communication Services', industry: 'Coin-Operated Amusement Devices' },
  '7996': { sector: 'Communication Services', industry: 'Amusement Parks' },
  '7997': { sector: 'Communication Services', industry: 'Membership Sports & Recreation Clubs' },
  '7999': { sector: 'Communication Services', industry: 'Miscellaneous Amusement & Recreation' },
  '8000': { sector: 'Healthcare', industry: 'Services' },
  '8010': { sector: 'Healthcare', industry: 'Offices & Clinics of Doctors of Medicine' },
  '8020': { sector: 'Healthcare', industry: 'Offices & Clinics of Dentists' },
  '8030': { sector: 'Healthcare', industry: 'Offices & Clinics of Doctors of Osteopathy' },
  '8040': { sector: 'Healthcare', industry: 'Offices & Clinics of Other Health Practitioners' },
  '8041': { sector: 'Healthcare', industry: 'Offices & Clinics of Chiropractors' },
  '8042': { sector: 'Healthcare', industry: 'Offices & Clinics of Optometrists' },
  '8043': { sector: 'Healthcare', industry: 'Offices & Clinics of Podiatrists' },
  '8049': { sector: 'Healthcare', industry: 'Offices & Clinics of Health Practitioners' },
  '8050': { sector: 'Healthcare', industry: 'Nursing & Personal Care Facilities' },
  '8051': { sector: 'Healthcare', industry: 'Skilled Nursing Care Facilities' },
  '8052': { sector: 'Healthcare', industry: 'Intermediate Care Facilities' },
  '8059': { sector: 'Healthcare', industry: 'Nursing & Personal Care Facilities' },
  '8060': { sector: 'Healthcare', industry: 'Hospitals' },
  '8062': { sector: 'Healthcare', industry: 'General Medical & Surgical Hospitals' },
  '8063': { sector: 'Healthcare', industry: 'Psychiatric Hospitals' },
  '8069': { sector: 'Healthcare', industry: 'Specialty Hospitals' },
  '8070': { sector: 'Healthcare', industry: 'Medical & Dental Laboratories' },
  '8071': { sector: 'Healthcare', industry: 'Medical Laboratories' },
  '8072': { sector: 'Healthcare', industry: 'Dental Laboratories' },
  '8080': { sector: 'Healthcare', industry: 'Home Health Care Services' },
  '8090': { sector: 'Healthcare', industry: 'Health & Allied Services' },
  '8093': { sector: 'Healthcare', industry: 'Specialty Outpatient Facilities' },
  '8099': { sector: 'Healthcare', industry: 'Health & Allied Services' },
  '8100': { sector: 'Consumer Cyclical', industry: 'Legal Services' },
  '8110': { sector: 'Consumer Cyclical', industry: 'Legal Services' },
  '8200': { sector: 'Consumer Cyclical', industry: 'Educational Services' },
  '8210': { sector: 'Consumer Cyclical', industry: 'Elementary & Secondary Schools' },
  '8220': { sector: 'Consumer Cyclical', industry: 'Colleges, Universities & Professional Schools' },
  '8221': { sector: 'Consumer Cyclical', industry: 'Colleges, Universities & Professional Schools' },
  '8230': { sector: 'Consumer Cyclical', industry: 'Libraries' },
  '8240': { sector: 'Consumer Cyclical', industry: 'Vocational Schools' },
  '8243': { sector: 'Consumer Cyclical', industry: 'Data Processing Schools' },
  '8244': { sector: 'Consumer Cyclical', industry: 'Business & Secretarial Schools' },
  '8249': { sector: 'Consumer Cyclical', industry: 'Vocational Schools' },
  '8290': { sector: 'Consumer Cyclical', industry: 'Schools & Educational Services' },
  '8300': { sector: 'Consumer Cyclical', industry: 'Social Services' },
  '8320': { sector: 'Consumer Cyclical', industry: 'Individual & Family Social Services' },
  '8330': { sector: 'Consumer Cyclical', industry: 'Job Training & Related Services' },
  '8350': { sector: 'Consumer Cyclical', industry: 'Child Day Care Services' },
  '8360': { sector: 'Consumer Cyclical', industry: 'Residential Care' },
  '8390': { sector: 'Consumer Cyclical', industry: 'Social Services' },
  '8400': { sector: 'Consumer Cyclical', industry: 'Museums, Botanical & Zoological Gardens' },
  '8410': { sector: 'Consumer Cyclical', industry: 'Museums & Art Galleries' },
  '8420': { sector: 'Consumer Cyclical', industry: 'Arboretums, Botanical & Zoological Gardens' },
  '8600': { sector: 'Consumer Cyclical', industry: 'Membership Organizations' },
  '8610': { sector: 'Consumer Cyclical', industry: 'Business Associations' },
  '8620': { sector: 'Consumer Cyclical', industry: 'Professional Membership Organizations' },
  '8630': { sector: 'Consumer Cyclical', industry: 'Labor Unions & Similar Labor Organizations' },
  '8640': { sector: 'Consumer Cyclical', industry: 'Civic, Social & Fraternal Associations' },
  '8650': { sector: 'Consumer Cyclical', industry: 'Political Organizations' },
  '8660': { sector: 'Consumer Cyclical', industry: 'Religious Organizations' },
  '8690': { sector: 'Consumer Cyclical', industry: 'Membership Organizations' },
  '8700': { sector: 'Consumer Cyclical', industry: 'Engineering, Accounting & Research Services' },
  '8710': { sector: 'Consumer Cyclical', industry: 'Engineering Services' },
  '8711': { sector: 'Consumer Cyclical', industry: 'Engineering Services' },
  '8712': { sector: 'Consumer Cyclical', industry: 'Architectural Services' },
  '8713': { sector: 'Consumer Cyclical', industry: 'Surveying Services' },
  '8720': { sector: 'Consumer Cyclical', industry: 'Accounting, Auditing & Bookkeeping' },
  '8730': { sector: 'Technology', industry: 'Research & Development Services' },
  '8731': { sector: 'Technology', industry: 'Commercial Physical & Biological Research' },
  '8732': { sector: 'Technology', industry: 'Commercial Economic, Sociological & Educational Research' },
  '8733': { sector: 'Technology', industry: 'Noncommercial Research Organizations' },
  '8734': { sector: 'Technology', industry: 'Testing Laboratories' },
  '8740': { sector: 'Consumer Cyclical', industry: 'Management Services' },
  '8741': { sector: 'Consumer Cyclical', industry: 'Management Services' },
  '8742': { sector: 'Consumer Cyclical', industry: 'Management Consulting Services' },
  '8743': { sector: 'Consumer Cyclical', industry: 'Public Relations Services' },
  '8744': { sector: 'Consumer Cyclical', industry: 'Facilities Support Management Services' },
  '8748': { sector: 'Consumer Cyclical', industry: 'Business Consulting Services' },
  '8800': { sector: 'Consumer Cyclical', industry: 'Private Households' },
  '8900': { sector: 'Consumer Cyclical', industry: 'Services' },
  '8910': { sector: 'Consumer Cyclical', industry: 'Engineering, Accounting & Research Services' },
  '8920': { sector: 'Consumer Cyclical', industry: 'Noncommercial Research Organizations' },
  '8930': { sector: 'Consumer Cyclical', industry: 'Accounting, Auditing & Bookkeeping' },
  '8990': { sector: 'Consumer Cyclical', industry: 'Services' },
  
  // Public Administration (91-99) - Usually not publicly traded
  '9100': { sector: 'Industrial', industry: 'Executive, Legislative & General Government' },
  '9200': { sector: 'Industrial', industry: 'Executive, Legislative & General Government' },
  '9300': { sector: 'Industrial', industry: 'Finance, Taxation & Monetary Policy' },
  '9400': { sector: 'Industrial', industry: 'Administration of Human Resources' },
  '9500': { sector: 'Industrial', industry: 'Environmental Quality & Housing' },
  '9600': { sector: 'Industrial', industry: 'Economic & Social Planning' },
  '9700': { sector: 'Industrial', industry: 'National Security & International Affairs' },
  '9900': { sector: 'Industrial', industry: 'Nonclassifiable Establishments' },
};

/**
 * Maps SIC code to sector and industry
 * Uses first 4 digits of SIC code for classification
 */
export function mapSICToSectorIndustry(sicCode: string | null | undefined): SICMapping | null {
  if (!sicCode) {
    return null;
  }

  // Normalize SIC code (take first 4 digits)
  const normalizedSIC = sicCode.padStart(4, '0').substring(0, 4);
  
  // Exact match
  if (SIC_MAP[normalizedSIC]) {
    return SIC_MAP[normalizedSIC];
  }

  // Try first 3 digits
  const firstThree = normalizedSIC.substring(0, 3) + '0';
  if (SIC_MAP[firstThree]) {
    return SIC_MAP[firstThree];
  }

  // Try first 2 digits (major division)
  const firstTwo = normalizedSIC.substring(0, 2) + '00';
  if (SIC_MAP[firstTwo]) {
    return SIC_MAP[firstTwo];
  }

  // Try first 1 digit (major group)
  const firstOne = normalizedSIC.substring(0, 1) + '000';
  if (SIC_MAP[firstOne]) {
    return SIC_MAP[firstOne];
  }

  // Default fallback
  return { sector: 'Other', industry: 'Unknown' };
}
