-- BullPen Academy — backfill seed for a course that predates this repo's
-- migration/seed history (inserted directly into the DB, not committed).
-- Content documented exactly as found; difficulty backfilled from NULL to
-- 'beginner' (matches migration 070's precedent for what-is-a-stock, and this
-- course's content is clearly beginner-level) — see the paired backfill
-- migration applied alongside this seed.
-- Re-runnable: ON CONFLICT DO NOTHING.

INSERT INTO academy_courses (slug, title, description, icon, color, order_index, difficulty, requires_pro, is_published) VALUES
  ('reading-a-stock-price', 'Reading a Stock Price', 'Every stock page is packed with numbers. Learn what price, market cap, volume, and 52-week high/low actually mean — and why they matter to you as an investor.', '📈', '#10b981', 1, 'beginner', FALSE, TRUE)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO academy_lessons (course_id, slug, title, type, order_index, xp_reward, content)
SELECT
  (SELECT id FROM academy_courses WHERE slug = 'reading-a-stock-price'),
  v.slug, v.title, v.type, v.order_index, v.xp_reward, v.content
FROM (VALUES
  ('stock-page-numbers', 'The Numbers on Every Stock Page', 'read', 0, 10, '{"funFact":"A 1% move in Apple''s stock price shifts its total market value by roughly $3 billion — in a single day.","sections":[{"text":"Every stock page shows a price and two change figures — a dollar amount and a percentage. If a stock closed at $100 yesterday and trades at $108 today, the dollar change is +$8 and the percentage change is +8%. The percentage is more useful: it lets you compare a $5 stock and a $500 stock on equal footing.","highlightedTerms":[{"term":"price","definition":"The current cost of one share. Changes continuously during market hours as buyers and sellers trade."},{"term":"change %","definition":"Today''s price move expressed as a percentage of yesterday''s closing price. The standard way to compare moves across different stocks."}]},{"text":"Market capitalisation — market cap — is simply the share price multiplied by the total number of shares outstanding. A $100 stock with 10 million shares = a $1 billion company. Market cap tells you the company''s size at a glance: mega-cap (Apple, Microsoft) sit above $1 trillion; large-cap above $10 billion; mid-cap $2–10 billion; small-cap below $2 billion.","highlightedTerms":[{"term":"market cap","definition":"Share price × total shares outstanding. The total market value of a company right now."},{"term":"shares outstanding","definition":"The total number of shares currently held by all investors, including insiders and institutions."}]},{"text":"The 52-week high and low show the price range over the past year. A stock near its 52-week high may be on a strong run — or getting expensive. One near its 52-week low might look cheap — or it might be in trouble. Volume tells you how many shares traded today. Unusually high volume often means something significant just happened.","highlightedTerms":[{"term":"52-week high/low","definition":"The highest and lowest prices the stock has traded at over the past 52 weeks. A useful reference for context."},{"term":"volume","definition":"The number of shares traded in a session. High volume on a big price move makes the move more credible."}]}]}'::jsonb),
  ('price-basics-quiz', 'Quick Check: Price Basics', 'quiz', 1, 20, '{"questions":[{"options":["4%","8%","54%","You need the market cap to calculate it"],"question":"A stock closed at $50 yesterday and trades at $54 today. What is the percentage change?","explanation":"Percentage change = (new − old) / old × 100. ($54 − $50) / $50 × 100 = 8%. The dollar change is $4, but the percentage change — 8% — is what makes it comparable to other stocks.","correctIndex":1},{"options":["$20 million","$500 million","$10 billion","$20 billion"],"question":"A company has 500 million shares outstanding and a share price of $20. What is its market cap?","explanation":"Market cap = price × shares outstanding. $20 × 500,000,000 = $10,000,000,000. A $10 billion company falls in the large-cap category.","correctIndex":2},{"options":["It''s definitely cheap — a great buy","It''s down significantly from its peak, which deserves investigation","The company will definitely recover to $200","The stock is going to zero"],"question":"A stock''s 52-week high is $200 and it trades at $90 today. What''s the most accurate takeaway?","explanation":"A big drop from the 52-week high is a signal to investigate — not automatically a reason to buy or sell. The business may have genuinely weakened, or the old price may have been inflated. Context matters.","correctIndex":1}]}'::jsonb),
  ('price-metrics-match', 'Match the Metrics', 'match', 2, 15, '{"pairs":[{"term":"Market Cap","definition":"Price × total shares outstanding"},{"term":"Volume","definition":"Number of shares traded today"},{"term":"52-week High","definition":"Highest price in the past year"},{"term":"Change %","definition":"Today''s move vs yesterday''s close"}]}'::jsonb),
  ('why-prices-move', 'Why Do Prices Move?', 'read', 3, 10, '{"funFact":"When the US Federal Reserve speaks about interest rates, stock prices across the entire market can shift billions of dollars in value within seconds — before most people finish reading the headline.","sections":[{"text":"Stock prices are set by supply and demand — every second the market is open. When more people want to buy a stock than sell it, the price rises. When more people want to sell, it falls. The exchange matches buyers and sellers in real time, which is why prices tick up and down continuously throughout the trading day.","highlightedTerms":[{"term":"supply and demand","definition":"The force behind all prices. More buyers than sellers pushes prices up; more sellers than buyers pushes them down."},{"term":"liquidity","definition":"How easily a stock can be bought or sold without moving the price. Heavily traded stocks like Apple are very liquid."}]},{"text":"Catalysts are events that suddenly shift that balance. Common ones: earnings reports (did the company beat or miss expectations?), product launches, management changes, economic data like inflation or unemployment, and central bank decisions on interest rates. A single headline can move a stock 10% or more in minutes.","highlightedTerms":[{"term":"catalyst","definition":"An event or announcement that triggers a significant, fast price move."},{"term":"earnings report","definition":"A quarterly update where a company reveals its revenue, profit, and outlook for the next quarter."}]},{"text":"Here''s the subtlest idea in investing: markets price in expectations, not just facts. A company can report record profits and still see its stock fall — if investors expected even better results. The price already reflected the optimism. When reality merely matches expectations, there''s no new reason to buy — and often a reason to sell.","highlightedTerms":[{"term":"priced in","definition":"When a widely-expected event is already reflected in the stock price before it officially happens."},{"term":"guidance","definition":"Management''s forecast for future revenue and profit. Often moves a stock more than the current quarter''s actual results."}]}]}'::jsonb),
  ('interpreting-a-move', 'Interpreting a Price Move', 'scenario', 4, 25, '{"setup":"NVIDIA is up 14% today. You open BullPen and see why: they just reported earnings that beat expectations by 40% and raised their guidance for the year. Your friend texts: ''Too late — you missed it. It''ll crash back down.'' What do you do?","choices":[{"label":"Buy immediately. The momentum is strong and I don''t want to miss more upside.","feedback":"Buying right after a 14% jump purely on momentum is FOMO — fear of missing out. The move may be completely justified by the new earnings data, or the stock may now be fully valued. Jumping in without understanding the valuation is speculation, not investing.","isCorrect":false},{"label":"Read the earnings report, check whether NVIDIA''s valuation still makes sense at today''s new price, then decide.","feedback":"This is exactly right. Understanding WHY the stock moved — and whether the new price is still reasonable given the improved business — is how thoughtful investors work. BullPen''s stock page shows updated financials and statistics to help you run that check.","isCorrect":true},{"label":"Wait for the stock to drop back to yesterday''s price before buying.","feedback":"This sounds disciplined, but it can be a trap. When a company genuinely improves — bigger earnings, raised guidance — yesterday''s price may never return because it reflected the old, weaker business. The new, higher price might be completely fair.","isCorrect":false}]}'::jsonb)
) AS v(slug, title, type, order_index, xp_reward, content)
ON CONFLICT (course_id, slug) DO NOTHING;
