-- BullPen Academy — course: "Researching with AI: Build a Thesis" (advanced, Pro)
-- Hand-authored + Zod-validated (scripts/_author_phase3.ts). Re-runnable: ON CONFLICT DO NOTHING.

INSERT INTO academy_courses (slug, title, description, icon, color, order_index, difficulty, requires_pro, is_published) VALUES
  ('ai-research', 'Researching with AI: Build a Thesis', 'AI can research a stock in seconds — if you ask well. Learn to turn a hunch into a real investment thesis, ask sharper questions, and verify every answer against its sources.', 'Sparkles', 'emerald', 11, 'advanced', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO academy_lessons (course_id, slug, title, type, order_index, xp_reward, content)
SELECT
  (SELECT id FROM academy_courses WHERE slug = 'ai-research'),
  v.slug, v.title, v.type, v.order_index, v.xp_reward, v.content
FROM (VALUES
  ('what-is-a-thesis', 'What Makes a Good Investment Thesis', 'read', 0, 10, '{"sections":[{"text":"An investment thesis is a short, honest argument for why you own — or want to own — a stock. If you can’t state it in a few sentences, you don’t have a thesis yet; you have a hunch. Writing it down is what turns a feeling into something you can test.","highlightedTerms":[{"term":"Investment Thesis","definition":"A clear, written argument for why a stock should do well — the reasons, the catalysts, and the risks — that you can check against reality over time."}]},{"text":"A good thesis has four parts: what the company actually does, why it will succeed (its edge), the catalysts that could prove you right, and the risks that could prove you wrong. Leaving out the last two is how hype masquerades as analysis.","highlightedTerms":[{"term":"Catalyst","definition":"A specific event — an earnings beat, a product launch, a new regulation — that could move a stock and confirm or break your thesis."}]},{"text":"The single most valuable line is “what would change my mind.” Deciding in advance what would make you sell protects you from clinging to a broken thesis out of pride when the facts turn against you.","highlightedTerms":[]},{"text":"A written thesis turns investing from gambling into a testable claim. When news breaks, you check it against your thesis instead of reacting to the price — calmer, and far more consistent.","highlightedTerms":[]}],"funFact":"Many professional investors keep a “thesis journal,” recording why they bought at the time — so later they can tell whether they were right for the right reasons, or just lucky."}'::jsonb),
  ('asking-better-questions', 'Asking Better Questions', 'read', 1, 10, '{"sections":[{"text":"AI research is only as good as the question you ask. “Is this a good buy?” earns you a vague, hedged answer. “What are the three biggest risks to this company’s main source of revenue?” earns you something you can actually act on.","highlightedTerms":[]},{"text":"Ask for the bear case on purpose. Our instinct is to look only for reasons we’re right — so deliberately ask the AI why you might be wrong. That’s how you stress-test a thesis instead of decorating it.","highlightedTerms":[{"term":"Bear Case","definition":"The argument for why a stock could fall or a thesis could fail. Seeking it out on purpose is how you pressure-test an idea."}]},{"text":"Break big questions into small ones. Instead of “should I buy this stock,” ask about the moat, the competition, the debt load, and the catalysts — one at a time. The answers assemble into a thesis you built, not one you were handed.","highlightedTerms":[{"term":"Moat","definition":"A durable competitive advantage — a brand, network, patent, or scale — that protects a company’s profits from competitors."}]},{"text":"Treat the AI as a fast research assistant, not an oracle. It gathers, summarizes, and points you to sources; you weigh it and decide. The goal is understanding you can defend — not a verdict handed down to you.","highlightedTerms":[]}],"funFact":"The quality of an answer often depends more on the question than on the model. Vague in, vague out — a precise question is the single biggest lever you have on useful research."}'::jsonb),
  ('sources-and-skepticism', 'Sources & Skepticism', 'read', 2, 10, '{"sections":[{"text":"The most dangerous research is the kind that only confirms what you already believe. Confirmation bias is our tendency to seek out agreeing views and quietly ignore the rest — and it’s how a bad thesis survives long after it should have died.","highlightedTerms":[{"term":"Confirmation Bias","definition":"The tendency to notice and trust information that agrees with what you already believe, while dismissing evidence that doesn’t."}]},{"text":"This is why sources matter. BullPen’s “Why Today?” answers come with citations, so you can click through and check a claim yourself rather than trusting a tidy summary. An answer you can’t verify is really just a rumor in a nicer font.","highlightedTerms":[]},{"text":"Stay alert to claims with no source, numbers that look suspiciously round, and anything phrased as a certainty about the future. Markets deal in probabilities, not promises — confident language is not the same as being right.","highlightedTerms":[]},{"text":"Skepticism isn’t cynicism. It’s holding every claim — the AI’s, the crowd’s, and your own — to one standard: where’s the evidence, and how would I know if it were wrong?","highlightedTerms":[]}],"funFact":"Research on investors keeps finding the same costly trap: the more certain people feel, the more they trade — and the worse they tend to do. Overconfidence has a price."}'::jsonb),
  ('ai-research-quiz', 'Quick Check: AI Research', 'quiz', 3, 20, '{"questions":[{"question":"Which question is likely to produce the most useful research?","options":["“Is this stock going to go up?”","“What are the biggest risks to this company’s main source of revenue?”","“Should I buy this?”","“Is this a good company?”"],"correctIndex":1,"explanation":"Specific, answerable questions produce specific, usable answers. Vague questions like “will it go up?” only earn vague, hedged replies."},{"question":"What is confirmation bias?","options":["Trusting only official company statements","Seeking out information that agrees with what you already believe, and ignoring the rest","Buying a stock after it’s confirmed to rise","Double-checking a number before acting"],"correctIndex":1,"explanation":"Confirmation bias is favouring evidence that supports your existing view. It’s why deliberately seeking the bear case is so valuable."},{"question":"Why do citations and sources matter in an AI research answer?","options":["They make the answer longer","They let you verify each claim yourself instead of trusting a summary","They guarantee the answer is correct","They’re only needed for legal reasons"],"correctIndex":1,"explanation":"Sources make an answer checkable. Without them you’re trusting a summary; with them you can click through and confirm — the difference between research and a rumor."},{"question":"Besides reasons to buy, what should every solid investment thesis include?","options":["A price prediction","The risks, and what would change your mind","A guaranteed return","The opinions of popular investors"],"correctIndex":1,"explanation":"A thesis without its risks and an exit condition is just cheerleading. Naming what would prove you wrong is what makes it honest and testable."}]}'::jsonb),
  ('research-with-ai-demo', 'Research a Move with AI', 'demo', 4, 25, '{"surface":"ai-research","fixtureId":"nvda-why-today","steps":[{"id":"intro","target":"ai-ask","title":"Start with a question","body":"Real research begins with a specific question. Here’s a stock that moved today — let’s ask why, exactly the way you would inside BullPen.","requiredAction":"none"},{"id":"ask","target":"ai-ask","title":"Ask why it moved","body":"Click to ask. BullPen searches the day’s news and explains the move in plain language — the raw material for a thesis.","requiredAction":"run-research"},{"id":"answer","target":"ai-answer","title":"Read the catalysts","body":"There’s your answer: the specific catalysts behind the move, summarized. Notice it’s concrete events, not a vague “sentiment improved.”","requiredAction":"none"},{"id":"sources","target":"ai-sources","title":"Verify the sources","body":"This is the part that matters most — every claim is backed by a source you can open and check. Verifying is what separates research from a rumor.","requiredAction":"none"},{"id":"wrap","target":"none","title":"Ask, read, verify, decide","body":"Do this for the questions that actually matter to your thesis — the risks, the catalysts, the moat — and you’re researching like a pro instead of guessing.","requiredAction":"none"}]}'::jsonb),
  ('build-and-defend-thesis', 'Build & Defend a Thesis', 'scenario', 5, 25, '{"setup":"A friend messages you: “Everyone online is saying this stock is going to the moon — the product is incredible and the CEO is a genius. You have to buy!” You happen to like the product too, and the excitement is contagious. Before you put money in, what’s the most disciplined next step?","choices":[{"label":"Buy now — a great product plus this much agreement makes the thesis obvious.","feedback":"A beloved product and a crowd of agreeing voices feel convincing, but that’s precisely where confirmation bias thrives. “Everyone agrees” isn’t a thesis, and enthusiasm this loud is often already reflected in the price. You haven’t tested a single risk yet.","isCorrect":false},{"label":"Write down why it might work and what could go wrong, then research the biggest risks with sources before deciding.","feedback":"Exactly the disciplined move. You’ve turned a hot tip into a testable thesis — reasons for and against — and you’re verifying the bear case with real sources before committing money. That’s researching, not hype-following.","isCorrect":true},{"label":"Ignore it completely — if a stock is this popular online, it’s probably a trap.","feedback":"Reflexive dismissal is just confirmation bias in reverse: rejecting an idea without evidence instead of accepting one without evidence. The disciplined path is neither believe nor dismiss — investigate with sources, then judge.","isCorrect":false}]}'::jsonb)
) AS v(slug, title, type, order_index, xp_reward, content)
ON CONFLICT (course_id, slug) DO NOTHING;
