/**
 * BullPen Academy — AI-assisted course generator.
 *
 * Drafts lesson content with Claude, validates EVERY lesson against the Zod
 * schemas in types/academy.ts, prefers canonical glossary definitions for
 * highlighted terms, and emits a reviewable .sql seed to stdout. Writes NOTHING
 * to the database — a human reviews the SQL before it is applied.
 *
 * Usage:
 *   1. Edit the OUTLINE constant below (or pass an outline JSON path as argv[2]).
 *   2. npm run generate-course > supabase/seeds/00N_academy_<slug>.sql
 *   3. Review the generated SQL for accuracy + tone.
 *   4. Apply via Supabase MCP apply_migration (or run the seed).
 *
 * Quality gate: invalid model output is re-prompted up to MAX_RETRIES with the
 * Zod error; if still invalid the script aborts (never emits broken SQL).
 */

import { config } from 'dotenv';
import { resolve } from 'path';
import { readFileSync } from 'fs';
config({ path: resolve(process.cwd(), '.env.local') });

import type { CourseOutline } from '../lib/academy/course-outline-types';
import { generateCourseLessons } from '../lib/academy/generate-course-content';

// ─── Default outline (edit me, or pass a JSON path as argv[2]) ─────────────────
// Example: course #2 in the roadmap. Replace freely.

const DEFAULT_OUTLINE: CourseOutline = {
  slug: 'etfs-and-crypto',
  title: 'Beyond Stocks: ETFs & Crypto',
  description:
    'Stocks aren\'t the only asset on BullPen. Learn what ETFs are, how they differ from picking individual stocks, and the basics of crypto and commodities.',
  icon: 'Layers',
  color: 'emerald',
  orderIndex: 7,
  difficulty: 'beginner',
  unitLabel: 'Foundations',
  lessons: [
    { slug: 'what-is-an-etf', title: 'What is an ETF?', type: 'read', topic: 'What an ETF (exchange-traded fund) is — a basket of stocks or bonds bought as a single share — how it differs from picking individual stocks, and what an expense ratio is.', xpReward: 10 },
    { slug: 'intro-crypto-commodities', title: 'Intro to Crypto & Commodities', type: 'read', topic: 'What a cryptocurrency represents differently from equity ownership (no company, no earnings), why crypto tends to be more volatile, and why BullPen also tracks commodities like gold and oil.', xpReward: 10 },
    { slug: 'beyond-stocks-quiz', title: 'Quick Check: Beyond Stocks', type: 'quiz', topic: 'Test understanding of ETFs, expense ratio, and crypto basics from the previous two lessons. 3 questions.', xpReward: 20 },
    { slug: 'asset-terms-match', title: 'Match the Asset Terms', type: 'match', topic: 'Match asset terms (ETF, Expense Ratio, Index Fund, Cryptocurrency, Commodity) to their plain-English definitions.', xpReward: 15 },
    { slug: 'stock-etf-or-both', title: 'Stock, ETF, or Both?', type: 'scenario', topic: 'A beginner wants broad exposure to the tech sector without picking individual winners and losers, and is deciding between buying one tech stock they like, a tech-sector ETF, or both. Reward matching the vehicle to the actual goal (broad exposure vs individual conviction).', xpReward: 25 },
  ],
};

// ─── SQL emission ───────────────────────────────────────────────────────────

/** Escape a JS value as a single-quoted SQL string literal (doubling quotes). */
function sqlStr(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

/** Escape a validated content object as a '{...}'::jsonb literal. */
function sqlJsonb(content: unknown): string {
  return `${sqlStr(JSON.stringify(content))}::jsonb`;
}

function emitSql(outline: CourseOutline, contents: unknown[]): string {
  const lines: string[] = [];
  lines.push(`-- BullPen Academy — generated course: "${outline.title}" (${outline.difficulty})`);
  lines.push(`-- Generated by scripts/generate-academy-course.ts. Review before applying.`);
  lines.push(`-- Re-runnable: ON CONFLICT DO NOTHING.`);
  lines.push('');
  lines.push(`INSERT INTO academy_courses (slug, title, description, icon, color, order_index, difficulty, requires_pro, unit_label, is_published) VALUES`);
  lines.push(
    `  (${sqlStr(outline.slug)}, ${sqlStr(outline.title)}, ${sqlStr(outline.description)}, ` +
    `${sqlStr(outline.icon)}, ${sqlStr(outline.color)}, ${outline.orderIndex}, ${sqlStr(outline.difficulty)}, ` +
    `${outline.requiresPro ? 'TRUE' : 'FALSE'}, ${outline.unitLabel ? sqlStr(outline.unitLabel) : 'NULL'}, TRUE)`
  );
  lines.push(`ON CONFLICT (slug) DO NOTHING;`);
  lines.push('');
  lines.push(`INSERT INTO academy_lessons (course_id, slug, title, type, order_index, xp_reward, content)`);
  lines.push(`SELECT`);
  lines.push(`  (SELECT id FROM academy_courses WHERE slug = ${sqlStr(outline.slug)}),`);
  lines.push(`  v.slug, v.title, v.type, v.order_index, v.xp_reward, v.content`);
  lines.push(`FROM (VALUES`);

  const rows = outline.lessons.map((lesson, i) => {
    return `  (${sqlStr(lesson.slug)}, ${sqlStr(lesson.title)}, ${sqlStr(lesson.type)}, ${i}, ${lesson.xpReward}, ${sqlJsonb(contents[i])})`;
  });
  lines.push(rows.join(',\n'));

  lines.push(`) AS v(slug, title, type, order_index, xp_reward, content)`);
  lines.push(`ON CONFLICT (course_id, slug) DO NOTHING;`);
  lines.push('');
  return lines.join('\n');
}

// ─── Main ───────────────────────────────────────────────────────────────────

function loadOutline(): CourseOutline {
  const path = process.argv[2];
  if (path) {
    const json = JSON.parse(readFileSync(resolve(process.cwd(), path), 'utf8'));
    return json as CourseOutline;
  }
  return DEFAULT_OUTLINE;
}

async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    process.stderr.write('❌ ANTHROPIC_API_KEY not set in .env.local\n');
    process.exit(1);
  }

  const outline = loadOutline();
  process.stderr.write(`\n📚 Generating "${outline.title}" — ${outline.lessons.length} lessons\n`);

  const contents = await generateCourseLessons(outline);

  process.stderr.write(`✅ All ${outline.lessons.length} lessons validated. Emitting SQL to stdout.\n\n`);
  process.stdout.write(emitSql(outline, contents));
}

main().catch((err) => {
  process.stderr.write(`\n❌ ${err.message}\n`);
  process.exit(1);
});
