import type { Metadata } from 'next';
import Link from 'next/link';
import { Logo } from '@/components/landing/Atoms';
import { Footer } from '@/components/landing/Footer';
import '@/components/landing/landing-styles.css';

export const metadata: Metadata = {
  title: 'Disclosures — BullPen',
  description: 'Important disclosures about BullPen\'s data, AI features, and brokerage connections.',
};

export default function DisclosuresPage() {
  return (
    <div className="bullpen-landing-root">
      <div className="content-layer">
        <header style={{ borderBottom: '1px solid var(--border)', padding: '20px 0' }}>
          <div className="wrap" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <Link href="/">
              <Logo size="sm" />
            </Link>
            <Link href="/" style={{ fontSize: 14, color: 'var(--fg-muted)' }}>
              ← Back to home
            </Link>
          </div>
        </header>

        <main className="wrap" style={{ padding: '56px 0 96px' }}>
          <div className="legal-doc">
            <h1>Disclosures</h1>

            <h2>Not investment advice</h2>
            <p>
              BullPen is not a registered investment advisor. Content on this platform — including
              stock data, health scores, AI-generated analysis, and educational material — is
              informational only and does not constitute financial, investment, tax, or legal advice.
              Nothing on BullPen should be relied upon as a recommendation to buy, sell, or hold any
              security.
            </p>

            <h2>AI-generated content</h2>
            <p>
              Some content on BullPen — including the AI research assistant, &quot;Why Today?&quot;
              price explanations, Daily Brief summaries, portfolio risk analysis, and AI Deep Dive
              reports — is generated by AI models. AI-generated content may be incomplete or contain
              errors, and should always be verified against primary sources before you rely on it for
              any decision.
            </p>

            <h2>Brokerage connections</h2>
            <p>
              When you connect a brokerage account through SnapTrade, the connection is read-only:
              BullPen never receives your brokerage login credentials, and neither BullPen nor
              SnapTrade can place trades, transfer funds, or take any other action on your brokerage
              account. We only receive account balance and holdings data to power your dashboard.
            </p>

            <h2>Market data</h2>
            <p>
              Market data is delayed up to 15 seconds on the Free plan. Data is provided by third-party
              vendors and, while we work with reputable providers, we cannot guarantee its accuracy or
              completeness.
            </p>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  );
}
