import type { Metadata } from 'next';
import Link from 'next/link';
import { Logo } from '@/components/landing/Atoms';
import { Footer } from '@/components/landing/Footer';
import '@/components/landing/landing-styles.css';

export const metadata: Metadata = {
  title: 'Disclosures',
  description: 'Important disclosures about BullPen\'s data, AI features, and brokerage connections.',
};

export default function DisclosuresPage() {
  return (
    <div className="bullpen-landing-root">
      <div className="content-layer">
        <header style={{ borderBottom: '1px solid var(--border)', padding: '20px 0' }}>
          <div className="wrap" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <Link href="/">
              <Logo size="sm" />
            </Link>
            <Link href="/" style={{ fontSize: 14, color: 'var(--fg-muted)' }}>
              ← Back to home
            </Link>
          </div>
        </header>

        <main className="wrap" style={{ padding: '56px 0 96px' }}>
          <div className="legal-doc">
            <h1>Disclosures</h1>

            <h2>Not investment advice</h2>
            <p>
              BullPen is not a registered investment advisor. Content on this platform — including
              stock data, health scores, AI-generated analysis, and educational material — is
              informational only and does not constitute financial, investment, tax, or legal advice.
              Nothing on BullPen should be relied upon as a recommendation to buy, sell, or hold any
              security.
            </p>

            <h2>AI-generated content</h2>
            <p>
              Some content on BullPen — including the AI research assistant, &quot;Why Today?&quot;
              price explanations, Daily Brief summaries, portfolio risk analysis, and AI Deep Dive
              reports — is generated by AI models. AI-generated content may be incomplete or contain
              errors, and should always be verified against primary sources before you rely on it for
              any decision.
            </p>

            <h2>Bull&apos;s Weekly Pick and its track record</h2>
            <p>
              Bull&apos;s Weekly Pick is a single stock idea selected each week by an AI model from
              market data, our own health scores and peer benchmarks, and public news. It is research
              output, not a recommendation, not personal financial advice, and not tailored to your
              circumstances, goals, or risk tolerance. Conviction ratings express the model&apos;s
              confidence in its own argument — they are not a probability, a forecast, or an
              endorsement.
            </p>
            <p>
              The published track record is calculated as follows. Each pick&apos;s entry price is the
              opening price of the first regular trading session on or after its publication date; it
              is recorded once and is not restated afterwards. The aggregate figure simulates
              investing an equal notional amount in every pick on its own entry date, expressed as a
              cumulative return against the total amount notionally invested, so that adding a new
              pick does not by itself change the reported return. The S&amp;P 500 comparison applies
              the identical schedule to SPY. Picks are never removed, closed early, or excluded from
              the calculation; a pick stops updating only if the security ceases to trade, in which
              case it is held at its final price.
            </p>
            <p>
              Reported returns are price-only. They exclude dividends, trading commissions, spreads,
              slippage, taxes, and any difference between the opening price used and the price at
              which an order would actually have been filled. An actual investor following these
              picks would very likely experience different results. Past performance is not a
              reliable indicator of future results, and over a small number of picks the reported
              figure reflects chance at least as much as it reflects skill.
            </p>

            <h2>Brokerage connections</h2>
            <p>
              When you connect a brokerage account through SnapTrade, the connection is read-only:
              BullPen never receives your brokerage login credentials, and neither BullPen nor
              SnapTrade can place trades, transfer funds, or take any other action on your brokerage
              account. We only receive account balance and holdings data to power your dashboard.
            </p>

            <h2>Market data</h2>
            <p>
              Market data is delayed up to 15 seconds on the Free plan. Data is provided by third-party
              vendors and, while we work with reputable providers, we cannot guarantee its accuracy or
              completeness.
            </p>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  );
}
