-- AI Deep Dives
-- Per-user saved analyst reports generated by the AI Deep Dive feature.
-- One row per generated report; users can save many per symbol (history).
-- Generation is gated/metered in the API route via lib/billing/quotas.ts
-- (free: 1/month, pro: soft cap). Viewing a saved row is always free.

CREATE TABLE IF NOT EXISTS public.stock_deep_dives (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol       TEXT        NOT NULL,
  company_name TEXT,
  lens         TEXT        NOT NULL DEFAULT 'full',
  report       JSONB       NOT NULL,            -- DeepDiveReport (headline, verdict, blocks)
  model        TEXT        NOT NULL,
  data_as_of   TIMESTAMPTZ,                     -- latest fiscal date of the fundamentals used
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Newest-first listing per user, and fast "latest for this symbol" lookups
CREATE INDEX IF NOT EXISTS idx_stock_deep_dives_user_created
  ON public.stock_deep_dives (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_deep_dives_user_symbol
  ON public.stock_deep_dives (user_id, symbol, created_at DESC);

COMMENT ON TABLE  public.stock_deep_dives IS 'Per-user AI-generated stock deep dive reports (analyst-grade structured blocks).';
COMMENT ON COLUMN public.stock_deep_dives.report IS 'DeepDiveReport JSON: headline, verdict {stance, confidence, oneLiner}, blocks[].';
COMMENT ON COLUMN public.stock_deep_dives.lens IS 'Analysis lens used: full | bull_bear | valuation | risk | for_me.';

ALTER TABLE public.stock_deep_dives ENABLE ROW LEVEL SECURITY;

-- User-owned CRUD. Server routes use the service role (bypasses RLS) and scope by
-- user_id explicitly; these policies cover any direct browser-client access.
CREATE POLICY "Users can read own deep dives"
  ON public.stock_deep_dives FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own deep dives"
  ON public.stock_deep_dives FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own deep dives"
  ON public.stock_deep_dives FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own deep dives"
  ON public.stock_deep_dives FOR DELETE
  USING (auth.uid() = user_id);
